import React, { useEffect, useState } from "react";
import { getStudentOverview } from "../lib/storage.js";
import { EmptyState, LoadingState, Notice, PageIntro, Panel, StatCard, StatusPill } from "../components/LmsUi.jsx";

export default function StudentDashboard({ view, session }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let alive = true; getStudentOverview().then((result) => alive && setData(result)).catch((err) => alive && setError(err.message)).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, []);
  if (loading) return <LoadingState />;
  if (error) return <Notice>{error}</Notice>;
  const student = data.student || session.user;
  return <div>{view === "overview" && <StudentOverview data={data} student={student} />}{view === "diary" && <StudentDiary data={data} />}{view === "tests" && <StudentTests data={data} />}{view === "results" && <StudentResults data={data} />}</div>;
}

function StudentOverview({ data, student }) {
  const todayHomework = (data.homework || []).filter((item) => !item.dueDate || item.dueDate >= new Date().toISOString().slice(0, 10)).slice(0, 4);
  return <><PageIntro eyebrow="Student workspace" title={`Hello, ${student.name?.split(" ")[0] || "there"}.`} description={`${student.className || "Your class"}${student.section ? ` · Section ${student.section}` : ""} · Here is what needs your attention.`} action={<StatusPill tone="orange">ID: {student.userId}</StatusPill>} /><div className="grid grid-cols-2 xl:grid-cols-4 gap-3 sm:gap-5"><StatCard label="Homework" value={data.homework?.length || 0} detail="Assignments to review" icon="⌁" tone="orange" /><StatCard label="Tests" value={data.tests?.length || 0} detail="Scheduled resources" icon="▣" tone="blue" /><StatCard label="Results" value={data.grades?.length || 0} detail="Marks available" icon="▤" tone="green" /><StatCard label="Attendance" value={attendancePercent(data.attendance)} detail="Recent attendance" icon="✓" tone="violet" /></div><div className="mt-6 grid xl:grid-cols-[1.15fr_.85fr] gap-5"><Panel title="Today's focus" description="Your latest homework and class updates.">{todayHomework.length ? <div className="space-y-3">{todayHomework.map((item) => <HomeworkCard key={item.id} item={item} />)}</div> : <EmptyState icon="✓" title="You are all caught up" text="New homework will appear here when your teacher posts it." />}</Panel><Panel title="Upcoming tests" description="Open a resource to prepare.">{data.tests?.length ? <div className="space-y-3">{data.tests.slice(0, 4).map((test) => <ResourceRow key={test.id} resource={test} />)}</div> : <EmptyState icon="▣" title="No tests posted" text="Your teacher's test resources will show here." />}</Panel></div></>;
}

function StudentDiary({ data }) { return <><PageIntro eyebrow="Learning" title="Diary & homework" description="Your teachers' assignments, notes and due dates." />{data.homework?.length ? <div className="grid md:grid-cols-2 gap-4">{data.homework.map((item) => <HomeworkCard key={item.id} item={item} expanded />)}</div> : <EmptyState icon="⌁" title="No diary entries yet" text="Check back after your teacher posts homework." />}</>; }
function StudentTests({ data }) { return <><PageIntro eyebrow="Learning" title="Tests" description="Scheduled tests and downloadable test-paper resources." />{data.tests?.length ? <div className="grid md:grid-cols-2 gap-4">{data.tests.map((test) => <ResourceCard key={test.id} resource={test} />)}</div> : <EmptyState icon="▣" title="No tests yet" text="Your scheduled tests will appear here." />}</>; }
function StudentResults({ data }) { const grouped = (data.grades || []).reduce((result, grade) => { const key = grade.subject || "Other"; (result[key] ||= []).push(grade); return result; }, {}); return <><PageIntro eyebrow="Progress" title="My results" description="Marks and feedback shared by your teachers." />{Object.keys(grouped).length ? <div className="grid md:grid-cols-2 gap-4">{Object.entries(grouped).map(([subject, grades]) => <Panel key={subject} title={subject} description={`${grades.length} assessment${grades.length === 1 ? "" : "s"}`}><div className="space-y-3">{grades.map((grade) => <div key={grade.id} className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-emerald-50 text-emerald-700 grid place-items-center font-black text-xs">{Math.round((grade.marks / grade.maxMarks) * 100)}%</div><div className="flex-1 min-w-0"><p className="text-sm font-bold truncate">{grade.assessment}</p><p className="text-xs text-slate-400">{grade.term}{grade.feedback ? ` · ${grade.feedback}` : ""}</p></div><span className="text-sm font-bold text-slate-700">{grade.marks}/{grade.maxMarks}</span></div>)}</div></Panel>)}</div> : <EmptyState icon="▤" title="No results yet" text="Marks will appear here when your teachers publish them." />}</>; }

function HomeworkCard({ item, expanded = false }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><StatusPill tone="orange">{item.subject}</StatusPill><h3 className="mt-3 font-bold text-slate-900">{item.title}</h3></div>{item.dueDate && <span className="text-[11px] font-bold text-slate-400 whitespace-nowrap">Due {item.dueDate}</span>}</div>{item.description && <p className={`mt-2 text-sm leading-6 text-slate-500 ${expanded ? "" : "line-clamp-2"}`}>{item.description}</p>}{item.attachmentUrl && <a href={item.attachmentUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs font-bold text-blue-600 hover:text-blue-800">Open assignment link ↗</a>}{item.attachmentData && <a href={item.attachmentData} download={item.attachmentName || "assignment"} className="mt-4 inline-flex text-xs font-bold text-blue-600 hover:text-blue-800">Download {item.attachmentName || "attachment"} ↓</a>}</article>; }
function ResourceRow({ resource }) { return <div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="w-9 h-9 rounded-xl bg-blue-100 text-blue-700 grid place-items-center font-bold">▣</span><div className="flex-1 min-w-0"><p className="text-sm font-bold truncate">{resource.title}</p><p className="text-xs text-slate-400">{resource.subject}</p></div>{resource.url && <a href={resource.url} target="_blank" rel="noreferrer" className="text-xs font-bold text-blue-600">Open</a>}</div>; }
function ResourceCard({ resource }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><StatusPill tone="blue">{resource.subject}</StatusPill><h3 className="mt-3 font-bold">{resource.title}</h3>{resource.description && <p className="mt-2 text-sm leading-6 text-slate-500">{resource.description}</p>}<div className="mt-4 flex gap-4">{resource.url && <a href={resource.url} target="_blank" rel="noreferrer" className="text-xs font-bold text-blue-600">Open link ↗</a>}{resource.fileData && <a href={resource.fileData} download={resource.fileName || "study-material"} className="text-xs font-bold text-blue-600">Download file ↓</a>}</div></article>; }
function attendancePercent(attendance) { const records = (attendance || []).flatMap((item) => item.records || []); if (!records.length) return "—"; return `${Math.round((records.filter((record) => record.status === "present").length / records.length) * 100)}%`; }