import React, { useEffect, useState } from "react";
import {
  addTeacherGrade,
  addTeacherHomework,
  addTeacherMaterial,
  getTeacherAttendance,
  getTeacherOverview,
  saveTeacherAttendance,
} from "../lib/storage.js";
import DiaryGenerator from "../components/DiaryGenerator.jsx";
import TestPaperGenerator from "../components/TestPaperGenerator.jsx";
import { EmptyState, Field, LoadingState, Notice, PageIntro, Panel, PrimaryButton, SelectField, StatCard, StatusPill, TextArea } from "../components/LmsUi.jsx";

const today = () => new Date().toISOString().slice(0, 10);
const blankGrade = { studentId: "", subject: "", assessment: "", marks: "", maxMarks: "100", term: "Current term", feedback: "" };
const blankHomework = { subject: "", title: "", description: "", dueDate: "", attachmentUrl: "", attachmentData: "", attachmentName: "" };
const blankMaterial = { subject: "", title: "", description: "", url: "", fileData: "", fileName: "", kind: "material" };

export default function TeacherDashboard({ view, session }) {
  const [overview, setOverview] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const school = overview?.school || session?.school;

  const load = async () => {
    try { setError(""); setOverview(await getTeacherOverview()); } catch (err) { setError(err.message); } finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const flash = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 3500); };
  if (loading) return <LoadingState />;
  if (error && !overview) return <Notice>{error}</Notice>;

  return <div>
    {error && <div className="mb-5"><Notice>{error}</Notice></div>}
    {notice && <div className="mb-5"><Notice type="success">{notice}</Notice></div>}
    {view === "overview" && <TeacherOverview overview={overview} />}
    {view === "attendance" && <AttendancePanel students={overview.students} onSaved={flash} />}
    {view === "gradebook" && <GradebookPanel overview={overview} onSaved={async (message) => { await load(); flash(message); }} />}
    {view === "homework" && <HomeworkPanel teacher={overview.teacher} onSaved={async (message) => { await load(); flash(message); }} />}
    {view === "materials" && <MaterialsPanel teacher={overview.teacher} onSaved={async (message) => { await load(); flash(message); }} />}
    {view === "generators" && <GeneratorsPanel school={school} schoolId={session.user.schoolId} />}
  </div>;
}

function TeacherOverview({ overview }) {
  const teacher = overview.teacher;
  return <><PageIntro eyebrow="Teacher workspace" title={`Good morning, ${teacher?.name || "Teacher"}.`} description={`${teacher?.className || "Your class"}${teacher?.section ? ` · Section ${teacher.section}` : ""} is all in one place today.`} action={<StatusPill tone="green">{teacher?.subjects?.length || 0} subjects</StatusPill>} /><div className="grid grid-cols-2 xl:grid-cols-4 gap-3 sm:gap-5"><StatCard label="My students" value={overview.students?.length || 0} detail="Students in your assigned class" icon="♧" tone="green" /><StatCard label="Homework posted" value={overview.homework?.length || 0} detail="Recent assignments" icon="⌁" tone="blue" /><StatCard label="Marks entered" value={overview.grades?.length || 0} detail="Recent gradebook records" icon="▤" tone="orange" /><StatCard label="Study items" value={overview.materials?.length || 0} detail="Materials and tests" icon="▣" tone="violet" /></div><div className="mt-6 grid xl:grid-cols-2 gap-5"><Panel title="Your class" description="Students connected to your assigned class and section."><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{overview.students?.length ? overview.students.slice(0, 8).map((student) => <div key={student.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="w-8 h-8 rounded-lg bg-white border border-slate-200 grid place-items-center text-xs font-bold text-slate-500">{student.rollNumber || "•"}</span><div className="min-w-0"><p className="text-sm font-bold truncate">{student.name}</p><p className="text-[11px] text-slate-400">{student.userId}</p></div></div>) : <div className="sm:col-span-2"><EmptyState icon="♧" title="No students assigned yet" text="Ask your admin to add students to your class." /></div>}</div></Panel><Panel title="Recent classroom activity" description="Your latest homework and study updates."><div className="space-y-3">{overview.homework?.slice(0, 4).map((item) => <Activity key={item.id} icon="⌁" title={item.title} detail={`${item.subject} · ${item.dueDate ? `Due ${item.dueDate}` : "No due date"}`} tone="green" />)}{overview.materials?.slice(0, 4).map((item) => <Activity key={item.id} icon={item.kind === "test" ? "▣" : "▤"} title={item.title} detail={`${item.subject} · ${item.kind === "test" ? "Test" : "Material"}`} tone="blue" />)}{!overview.homework?.length && !overview.materials?.length && <EmptyState icon="⌁" title="Nothing posted yet" text="Use Homework or Study material to share your first update." />}</div></Panel></div></>;
}
function Activity({ icon, title, detail, tone }) { return <div className="flex gap-3 items-center"><span className={`w-9 h-9 rounded-xl grid place-items-center font-bold ${tone === "green" ? "bg-emerald-50 text-emerald-700" : "bg-blue-50 text-blue-700"}`}>{icon}</span><div className="min-w-0"><p className="text-sm font-bold truncate">{title}</p><p className="text-xs text-slate-400">{detail}</p></div></div>; }

function AttendancePanel({ students, onSaved }) {
  const [date, setDate] = useState(today()); const [records, setRecords] = useState({}); const [loading, setLoading] = useState(false); const [fetching, setFetching] = useState(true);
  const loadDate = async (nextDate) => { setFetching(true); try { const data = await getTeacherAttendance(nextDate); const existing = Object.fromEntries((data.record?.records || []).map((record) => [record.studentId, record.status])); setRecords(Object.fromEntries((data.students || students).map((student) => [student.id, existing[student.id] || "present"]))); } catch (err) { window.alert(err.message); } finally { setFetching(false); } };
  useEffect(() => { loadDate(date); }, [date]);
  const submit = async () => { setLoading(true); try { await saveTeacherAttendance({ date, records: Object.entries(records).map(([studentId, status]) => ({ studentId, status })) }); onSaved(`Attendance saved for ${date}.`); } catch (err) { window.alert(err.message); } finally { setLoading(false); } };
  return <><PageIntro eyebrow="Classroom" title="Attendance" description="Mark every learner as present, absent or late. Changes are saved for the selected date." action={<div className="w-full sm:w-44"><input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold outline-none focus:ring-2 focus:ring-emerald-100" /></div>} /><Panel title="Daily register" description="Students are loaded from your assigned class.">{fetching ? <LoadingState /> : students?.length ? <><div className="flex flex-wrap gap-2 mb-5"><button onClick={() => setRecords(Object.fromEntries(students.map((student) => [student.id, "present"])))} className="rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Mark all present</button><button onClick={() => setRecords(Object.fromEntries(students.map((student) => [student.id, "absent"])))} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700">Mark all absent</button></div><div className="space-y-2">{students.map((student) => <div key={student.id} className="flex flex-col sm:flex-row sm:items-center gap-3 rounded-2xl border border-slate-100 p-3"><div className="flex items-center gap-3 flex-1"><span className="w-8 h-8 rounded-lg bg-slate-100 grid place-items-center text-xs font-bold text-slate-500">{student.rollNumber || "•"}</span><p className="text-sm font-bold">{student.name}</p></div><div className="grid grid-cols-3 rounded-xl bg-slate-100 p-1 gap-1">{["present", "late", "absent"].map((status) => <button key={status} onClick={() => setRecords((current) => ({ ...current, [student.id]: status }))} className={`rounded-lg px-3 py-2 text-[11px] font-bold capitalize transition ${records[student.id] === status ? status === "present" ? "bg-white text-emerald-700 shadow-sm" : status === "late" ? "bg-white text-orange-600 shadow-sm" : "bg-white text-red-600 shadow-sm" : "text-slate-400 hover:text-slate-600"}`}>{status}</button>)}</div></div>)}</div><div className="mt-5 flex justify-end"><PrimaryButton tone="green" onClick={submit} disabled={loading}>{loading ? "Saving…" : "Save attendance"}</PrimaryButton></div></> : <EmptyState icon="✓" title="No students in this class" text="Ask your administrator to assign students before taking attendance." />}</Panel></>;
}

function GradebookPanel({ overview, onSaved }) {
  const [form, setForm] = useState(blankGrade); const [saving, setSaving] = useState(false); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await addTeacherGrade(form); setForm(blankGrade); onSaved("Grade added to the gradebook."); } catch (err) { window.alert(err.message); } finally { setSaving(false); } };
  return <><PageIntro eyebrow="Classroom" title="Gradebook" description="Enter marks for any learner in your assigned class. Students will see results on their dashboard." /><div className="grid xl:grid-cols-[.8fr_1.2fr] gap-5"><Panel title="Enter marks" description="Marks must be between zero and the maximum marks."><form onSubmit={submit} className="space-y-4"><SelectField label="Student" value={form.studentId} onChange={(value) => update("studentId", value)} options={(overview.students || []).map((student) => ({ value: student.id, label: `${student.name}${student.rollNumber ? ` · ${student.rollNumber}` : ""}` }))} required /><div className="grid grid-cols-2 gap-3"><Field label="Subject" value={form.subject} onChange={(value) => update("subject", value)} placeholder="Math" required /><Field label="Assessment" value={form.assessment} onChange={(value) => update("assessment", value)} placeholder="Unit 1" required /><Field label="Marks" type="number" min="0" value={form.marks} onChange={(value) => update("marks", value)} placeholder="18" required /><Field label="Maximum" type="number" min="1" value={form.maxMarks} onChange={(value) => update("maxMarks", value)} placeholder="20" required /></div><Field label="Term" value={form.term} onChange={(value) => update("term", value)} placeholder="Current term" /><TextArea label="Feedback (optional)" value={form.feedback} onChange={(value) => update("feedback", value)} placeholder="A short note for the student" rows={2} /><PrimaryButton type="submit" tone="green" disabled={saving}>{saving ? "Saving…" : "Save marks"}</PrimaryButton></form></Panel><Panel title="Recent entries" description="Latest marks entered by you."><div className="space-y-2">{overview.grades?.length ? overview.grades.map((grade) => <div key={grade.id} className="rounded-2xl border border-slate-100 p-4 flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-blue-50 text-blue-700 grid place-items-center font-black text-sm">{Math.round((grade.marks / grade.maxMarks) * 100)}%</div><div className="min-w-0 flex-1"><p className="text-sm font-bold truncate">{grade.subject} · {grade.assessment}</p><p className="text-xs text-slate-400">{studentName(overview.students, grade.studentId)} · {grade.term}</p></div><StatusPill tone={grade.marks / grade.maxMarks >= .5 ? "green" : "red"}>{grade.marks} / {grade.maxMarks}</StatusPill></div>) : <EmptyState icon="▤" title="No grades yet" text="Your saved marks will appear here." />}</div></Panel></div></>;
}

function HomeworkPanel({ teacher, onSaved }) {
  const [form, setForm] = useState(blankHomework); const [file, setFile] = useState(null); const [saving, setSaving] = useState(false); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const chooseFile = async (event) => { const selected = event.target.files?.[0]; if (!selected) return; if (selected.size > 4 * 1024 * 1024) return window.alert("Please choose a file under 4MB."); const data = await fileToDataUrl(selected); setFile(selected); setForm((current) => ({ ...current, attachmentData: data, attachmentName: selected.name })); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await addTeacherHomework(form); setForm(blankHomework); setFile(null); onSaved("Homework published for your class."); } catch (err) { window.alert(err.message); } finally { setSaving(false); } };
  return <><PageIntro eyebrow="Classroom" title="Homework" description={`Post an assignment or note for ${teacher?.className || "your class"}${teacher?.section ? ` · ${teacher.section}` : ""}.`} /><Panel title="Publish homework" description="Students see new homework in their Diary & homework view."><form onSubmit={submit} className="grid md:grid-cols-2 gap-4"><Field label="Subject" value={form.subject} onChange={(value) => update("subject", value)} placeholder="English" required /><Field label="Title" value={form.title} onChange={(value) => update("title", value)} placeholder="Read chapter 3" required /><Field label="Due date" type="date" value={form.dueDate} onChange={(value) => update("dueDate", value)} /><Field label="Optional link" value={form.attachmentUrl} onChange={(value) => update("attachmentUrl", value)} placeholder="https://…" /><TextArea className="md:col-span-2" label="Instructions or notes" value={form.description} onChange={(value) => update("description", value)} placeholder="Tell students what to complete…" rows={4} /><FilePicker label="Attach a worksheet" file={file} onChange={chooseFile} /><div className="md:col-span-2 flex justify-end"><PrimaryButton type="submit" tone="green" disabled={saving}>{saving ? "Publishing…" : "Publish homework"}</PrimaryButton></div></form></Panel></>;
}

function MaterialsPanel({ teacher, onSaved }) {
  const [form, setForm] = useState(blankMaterial); const [file, setFile] = useState(null); const [saving, setSaving] = useState(false); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const chooseFile = async (event) => { const selected = event.target.files?.[0]; if (!selected) return; if (selected.size > 4 * 1024 * 1024) return window.alert("Please choose a file under 4MB."); const data = await fileToDataUrl(selected); setFile(selected); setForm((current) => ({ ...current, fileData: data, fileName: selected.name })); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await addTeacherMaterial(form); setForm(blankMaterial); setFile(null); onSaved(form.kind === "test" ? "Test resource published." : "Study material published."); } catch (err) { window.alert(err.message); } finally { setSaving(false); } };
  return <><PageIntro eyebrow="Resources" title="Study material & tests" description="Share a PDF, link or test resource with the students in your class." /><Panel title="Publish a resource" description="Use the Test type for a scheduled test link or downloadable paper."><form onSubmit={submit} className="grid md:grid-cols-2 gap-4"><SelectField label="Resource type" value={form.kind} onChange={(value) => update("kind", value)} options={[{ value: "material", label: "Study material" }, { value: "test", label: "Test / paper" }]} /><Field label="Subject" value={form.subject} onChange={(value) => update("subject", value)} placeholder="Science" required /><Field className="md:col-span-2" label="Title" value={form.title} onChange={(value) => update("title", value)} placeholder="Chapter 2 revision PDF" required /><Field label="Link" value={form.url} onChange={(value) => update("url", value)} placeholder="https://…" /><FilePicker label="Upload PDF or file" file={file} onChange={chooseFile} /><TextArea className="md:col-span-2" label="Description" value={form.description} onChange={(value) => update("description", value)} placeholder="What should students focus on?" rows={3} /><div className="md:col-span-2 flex justify-end"><PrimaryButton type="submit" tone="green" disabled={saving}>{saving ? "Publishing…" : "Publish resource"}</PrimaryButton></div></form></Panel><p className="mt-4 text-xs text-slate-400">Tip: the existing Test Paper Generator remains available in the Generators section. You can publish its downloaded Word file here as a test resource.</p></>;
}

function GeneratorsPanel({ school, schoolId }) { const [mode, setMode] = useState("diary"); return <><PageIntro eyebrow="Tools" title="Existing generators" description="Your original Daily Home Work Diary and Test Paper Generator remain available inside the teacher workspace." action={<div className="flex rounded-xl bg-slate-100 p-1"><button onClick={() => setMode("diary")} className={`rounded-lg px-3 py-2 text-xs font-bold ${mode === "diary" ? "bg-white text-emerald-700 shadow-sm" : "text-slate-500"}`}>Diary</button><button onClick={() => setMode("testpaper")} className={`rounded-lg px-3 py-2 text-xs font-bold ${mode === "testpaper" ? "bg-white text-emerald-700 shadow-sm" : "text-slate-500"}`}>Test paper</button></div>} />{mode === "diary" ? <DiaryGenerator school={school} schoolId={schoolId} /> : <TestPaperGenerator school={school} />}</>; }

function FilePicker({ label, file, onChange }) { return <label className="block"><span className="text-xs font-semibold text-slate-500">{label}</span><input type="file" accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" onChange={onChange} className="mt-1.5 block w-full rounded-xl border border-dashed border-slate-300 bg-slate-50 px-3 py-2.5 text-xs text-slate-500 file:mr-3 file:rounded-lg file:border-0 file:bg-white file:px-2 file:py-1 file:text-xs file:font-bold" />{file && <span className="mt-1 block text-[11px] text-emerald-600">Attached: {file.name}</span>}</label>; }
function fileToDataUrl(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
function studentName(students, id) { return students.find((student) => student.id === id)?.name || "Student"; }
